name: ci-pipeline

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
    build:
      runs-on: [self-hosted ,Linux]

      steps:
        - name: checkout code
          uses: actions/checkout@v6

        - name: node modules install and Build
          run: |
            npm i
            npm run build


    test:
      needs: build
      runs-on: [self-hosted ,Linux]
      if: ${{ needs.build.result == 'Build Successful' }}
      

      steps:
        - name: checkout code
          uses: actions/checkout@v6

        - name: Test case run
          run: npm test


    start:
      needs: test
      runs-on: [self-hosted ,Linux]
      if: ${{ needs.test.result == 'passed' }}

      steps:
        - name: checkout code
          uses: actions/checkout@v6

        - name: build app.js 
          run: npm start
      
        
      
 
  
